name: "Deploy"

on:
  workflow_run:
    workflows: ["Build and Test", "CodeQL"]
    branches: [main]
    types:
      - completed
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Starting deploy'
  deploy:
    needs: [build-and-test, lint]
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: npm run build

      - name: Deploy to Vercel
        uses: mondnet/vercel-action@v20
        with:
          github-token: ${{ secrets.GH_PAT }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          alias-domains: ${{ secrets.ALIAS_DOMAIN }}
          github-comment: false
          working-directory: ./public
          vercel-args: '--prod'
