name: "Deploy"

on:
  workflow_run:
    workflows: ["Build and Test", "CodeQL"]
    branches: [main]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install depencencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Install Vercel CLI
        run: npm i -g vercel

      - name: Deploy to Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm

      - name: The end
        run: echo 'All good'
